CREATE DATABASE navychart;

USE navychart;

CREATE TABLE Users (
	ID INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	passwrd VARCHAR(200) NOT NULL,
	fName VARCHAR(40) NOT NULL,
	lName VARCHAR(40) NOT NULL,
	email VARCHAR(60) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Oceans (
	ID INT NOT NULL AUTO_INCREMENT,
	summary VARCHAR(240) NOT NULL,
	timetag TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);

CREATE TABLE Tags (
	ID INT NOT NULL AUTO_INCREMENT,
	tag VARCHAR(40) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE TagsToOceans (
	ID INT NOT NULL AUTO_INCREMENT,
	tag_ID INT NOT NULL,
	ocean_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (tag_ID) REFERENCES Tags(ID),
	FOREIGN KEY (ocean_ID) REFERENCES Oceans(ID)
);

CREATE TABLE Bookmarks (
	ID INT NOT NULL AUTO_INCREMENT,
	user_ID INT NOT NULL,
	ocean_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (user_ID) REFERENCES Users(ID),
	FOREIGN KEY (ocean_ID) REFERENCES Oceans(ID)
);

CREATE TABLE Painted (
	ID INT NOT NULL AUTO_INCREMENT,
	user_ID INT NOT NULL,
	ocean_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (user_ID) REFERENCES Users(ID),
	FOREIGN KEY (ocean_ID) REFERENCES Oceans(ID)
);

CREATE TABLE Messages (
	ID INT NOT NULL AUTO_INCREMENT,
	content TEXT NOT NULL,
	user_ID INT NOT NULL,
	ocean_ID INT NOT NULL,
	timetag TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (user_ID) REFERENCES Users(ID),
	FOREIGN KEY (ocean_ID) REFERENCES Oceans(ID)
);

INSERT INTO Users(username, passwrd, fName, lName, email)
VALUES ("limon95c", "tT5IiSGBhKtcYPnNoZpoBQ==:~‰(u¥,Y£µˆ0kÃ½", "Jorge", "Limón Cabrera", "j.limon.cabrera@gmail.com");